# Template workflow file to use in repo we want to generate image.
name: Generate Mockup Gif Laptop

on:
  push:
    branches: [main]

jobs:
  generate-gif:
    runs-on: ubuntu-latest

    steps:
      - name: dispatch generator
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: gif-mockup-laptop-generator
          repo: myusf01/ss-pipe
          token: ${{ secrets.FLOW_TOKEN }}
          inputs: '{ "repo": "${{ github.repository }}" }'
